// lib/server.js
//
// HTTP + WebSocket server exposing Iris to remote clients (e.g. iris-mobile).
// Runs alongside the Electron window, so the desktop renderer and any remote
// clients share the same AgentManager + Store instance. Designed to be
// started, stopped, and reconfigured at runtime from settings.
//
// Auth model: a single long-lived bearer token, generated by main.js on first
// enable. All non-/health endpoints require `Authorization: Bearer <token>`.
// WS upgrades read the token from the `?token=<...>` query parameter (browsers
// can't set custom headers on WebSocket constructor).
//
// Routes:
//   GET  /health         — unauthenticated liveness probe
//   GET  /api/v1/agents             — list agents
//   GET  /api/v1/agents/:id         — single agent + messages
//   GET  /api/v1/fs/tree            — directory tree (cwd-rooted)
//   GET  /api/v1/fs/file            — single file content
//   GET  /api/v1/memory             — CLAUDE.md content
//   GET  /api/v1/app/version        — Iris version
//   POST /api/v1/agents/:id/messages  body {message}
//   POST /api/v1/agents/:id/stop
//   POST /api/v1/agents/:id/resume
//   WS   /ws?token=...    — event stream; client sends {type:"subscribe",agentIds:[...]}

const express = require("express");
const http = require("http");
const crypto = require("crypto");
const { WebSocketServer } = require("ws");

const fsBrowser = require("./fs-browser.js");
const memoryHelper = require("./claude-md-memory.js");
const { Journal } = require("./memory/journal.js");

let state = null;

function timingSafeEqualString(a, b) {
  if (typeof a !== "string" || typeof b !== "string") return false;
  // Length comparison leaks length information, which is unavoidable for
  // variable-length tokens; our tokens are fixed-length base64url so this
  // is effectively constant-time in practice.
  const ba = Buffer.from(a);
  const bb = Buffer.from(b);
  if (ba.length !== bb.length) return false;
  return crypto.timingSafeEqual(ba, bb);
}

function startServer({ port, host, manager, store, dataDir, version, getAuth }) {
  if (state) {
    return Promise.resolve({ port: state.port, host: state.host, already: true });
  }
  if (typeof getAuth !== "function") {
    return Promise.reject(new Error("startServer: getAuth callback required"));
  }

  const app = express();
  app.disable("x-powered-by");
  app.use(express.json({ limit: "1mb" }));

  // Permissive CORS for the mobile app and any browser-based admin tool.
  // Tokens themselves are the security boundary; CORS only governs which
  // origins a *browser* lets read responses, and we expect non-browser
  // (React Native fetch) or trusted browser clients.
  app.use((req, res, next) => {
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Headers", "Authorization, Content-Type");
    res.setHeader("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
    if (req.method === "OPTIONS") return res.sendStatus(204);
    next();
  });

  // Liveness probe. Intentionally unauthenticated so mobile clients can
  // confirm reachability before sending the bearer token.
  app.get("/health", (_req, res) => {
    const auth = getAuth();
    res.json({
      ok: true,
      version: version || null,
      requiresToken: !!auth.enabled,
    });
  });

  // Bearer-token middleware for everything else.
  app.use((req, res, next) => {
    const auth = getAuth();
    if (!auth.enabled) {
      return res.status(503).json({ error: "remote_access_disabled" });
    }
    if (!auth.token) {
      return res.status(503).json({ error: "no_token_configured" });
    }
    const header = req.headers.authorization || "";
    const m = /^Bearer\s+(.+)$/i.exec(header);
    if (!m) {
      return res.status(401).json({ error: "missing_token" });
    }
    if (!timingSafeEqualString(m[1], auth.token)) {
      return res.status(401).json({ error: "invalid_token" });
    }
    next();
  });

  // ── REST routes ────────────────────────────────────────
  const api = express.Router();

  api.get("/app/version", (_req, res) => {
    res.json({ version: version || null });
  });

  api.get("/agents", (_req, res) => {
    if (!manager) return res.status(503).json({ error: "manager_unavailable" });
    try { res.json({ agents: manager.list() }); }
    catch (err) { res.status(500).json({ error: String(err.message || err) }); }
  });

  api.get("/agents/:id", (req, res) => {
    if (!manager) return res.status(503).json({ error: "manager_unavailable" });
    const agent = manager.get(req.params.id);
    if (!agent) return res.status(404).json({ error: "not_found" });
    res.json({ agent });
  });

  api.get("/fs/tree", (req, res) => {
    const cwd = String(req.query.cwd || "");
    const depth = Number(req.query.depth) || 2;
    const showHidden = req.query.hidden === "1" || req.query.hidden === "true";
    const roots = fsBrowser.getAllowedRoots(manager);
    const result = fsBrowser.listTree(cwd, { depth, roots, showHidden });
    if (!result.ok) return res.status(result.error === "not_allowed" ? 403 : 400).json(result);
    res.json(result);
  });

  api.get("/fs/file", (req, res) => {
    const target = String(req.query.path || "");
    const roots = fsBrowser.getAllowedRoots(manager);
    const result = fsBrowser.readFileForRemote(target, { roots });
    if (!result.ok) {
      const code = result.error === "not_allowed" ? 403
        : result.error === "not_found" ? 404
        : result.error === "too_large" ? 413
        : 400;
      return res.status(code).json(result);
    }
    res.json(result);
  });

  api.get("/memory", (req, res) => {
    const cwd = String(req.query.cwd || "");
    const roots = fsBrowser.getAllowedRoots(manager);
    // Same allow-list as fs/file: cwd must be under an agent root.
    const norm = fsBrowser.normalizePath(cwd);
    if (!norm || !fsBrowser.isAllowed(norm, roots)) {
      return res.status(403).json({ ok: false, error: "not_allowed" });
    }
    const result = memoryHelper.readMemory(norm);
    res.json(result);
  });

  // ── Mutations ──
  api.post("/agents/:id/messages", (req, res) => {
    if (!manager) return res.status(503).json({ error: "manager_unavailable" });
    const id = req.params.id;
    const message = req.body && typeof req.body.message === "string" ? req.body.message : "";
    if (!message.trim()) return res.status(400).json({ error: "message_required" });
    if (!manager.get(id)) return res.status(404).json({ error: "agent_not_found" });
    try {
      manager.sendMessage(id, message);
      res.json({ ok: true });
    } catch (err) {
      res.status(500).json({ error: String(err.message || err) });
    }
  });

  api.post("/agents/:id/stop", (req, res) => {
    if (!manager) return res.status(503).json({ error: "manager_unavailable" });
    try {
      manager.stop(req.params.id);
      res.json({ ok: true });
    } catch (err) {
      res.status(500).json({ error: String(err.message || err) });
    }
  });

  api.post("/agents/:id/resume", (req, res) => {
    if (!manager) return res.status(503).json({ error: "manager_unavailable" });
    try {
      manager.resume(req.params.id);
      res.json({ ok: true });
    } catch (err) {
      res.status(500).json({ error: String(err.message || err) });
    }
  });

  // ── Journal (people / goals / notes) ──
  // Powers remote check-ins like "how's the gold progress?" — the client can
  // poll /journal/summary or call /journal/goals/:id to get the full history.
  // All routes lazily instantiate Journal so a missing dataDir surfaces as a
  // clean 503 instead of crashing the server.
  function getJournal() {
    if (!dataDir) return null;
    try { return new Journal({ dataDir }); } catch { return null; }
  }

  api.get("/journal/summary", (_req, res) => {
    const j = getJournal();
    if (!j) return res.status(503).json({ error: "journal_unavailable" });
    try { res.json(j.buildSummary()); }
    catch (err) { res.status(500).json({ error: String(err.message || err) }); }
  });

  api.get("/journal/people", (_req, res) => {
    const j = getJournal();
    if (!j) return res.status(503).json({ error: "journal_unavailable" });
    try { res.json({ people: j.listPeople() }); }
    catch (err) { res.status(500).json({ error: String(err.message || err) }); }
  });

  api.get("/journal/people/:name", (req, res) => {
    const j = getJournal();
    if (!j) return res.status(503).json({ error: "journal_unavailable" });
    const p = j.getPerson(req.params.name);
    if (!p) return res.status(404).json({ error: "not_found" });
    res.json({ person: p });
  });

  api.post("/journal/people", (req, res) => {
    const j = getJournal();
    if (!j) return res.status(503).json({ error: "journal_unavailable" });
    const { name, relationship, aliases } = req.body || {};
    if (!name) return res.status(400).json({ error: "name_required" });
    try { res.json({ person: j.upsertPerson(name, { relationship, aliases }) }); }
    catch (err) { res.status(400).json({ error: String(err.message || err) }); }
  });

  api.post("/journal/people/:name/notes", (req, res) => {
    const j = getJournal();
    if (!j) return res.status(503).json({ error: "journal_unavailable" });
    const text = req.body && typeof req.body.text === "string" ? req.body.text : "";
    if (!text.trim()) return res.status(400).json({ error: "text_required" });
    try { res.json({ note: j.addPersonNote(req.params.name, text) }); }
    catch (err) { res.status(404).json({ error: String(err.message || err) }); }
  });

  api.get("/journal/goals", (req, res) => {
    const j = getJournal();
    if (!j) return res.status(503).json({ error: "journal_unavailable" });
    const status = typeof req.query.status === "string" ? req.query.status : null;
    try { res.json({ goals: status ? j.listGoals({ status }) : j.listGoals() }); }
    catch (err) { res.status(500).json({ error: String(err.message || err) }); }
  });

  api.get("/journal/goals/:id", (req, res) => {
    const j = getJournal();
    if (!j) return res.status(503).json({ error: "journal_unavailable" });
    const g = j.getGoal(req.params.id);
    if (!g) return res.status(404).json({ error: "not_found" });
    res.json({ goal: g });
  });

  api.post("/journal/goals", (req, res) => {
    const j = getJournal();
    if (!j) return res.status(503).json({ error: "journal_unavailable" });
    const { title, description, status, dueAt } = req.body || {};
    if (!title) return res.status(400).json({ error: "title_required" });
    try { res.json({ goal: j.createGoal({ title, description, status, dueAt }) }); }
    catch (err) { res.status(400).json({ error: String(err.message || err) }); }
  });

  api.patch("/journal/goals/:id", (req, res) => {
    const j = getJournal();
    if (!j) return res.status(503).json({ error: "journal_unavailable" });
    try { res.json({ goal: j.updateGoal(req.params.id, req.body || {}) }); }
    catch (err) { res.status(400).json({ error: String(err.message || err) }); }
  });

  api.post("/journal/goals/:id/notes", (req, res) => {
    const j = getJournal();
    if (!j) return res.status(503).json({ error: "journal_unavailable" });
    const text = req.body && typeof req.body.text === "string" ? req.body.text : "";
    if (!text.trim()) return res.status(400).json({ error: "text_required" });
    try { res.json({ note: j.addGoalNote(req.params.id, text) }); }
    catch (err) { res.status(404).json({ error: String(err.message || err) }); }
  });

  api.get("/journal/notes", (req, res) => {
    const j = getJournal();
    if (!j) return res.status(503).json({ error: "journal_unavailable" });
    const limit = Math.max(1, Math.min(200, Number(req.query.limit) || 20));
    res.json({ notes: j.recentNotes(limit) });
  });

  api.post("/journal/notes", (req, res) => {
    const j = getJournal();
    if (!j) return res.status(503).json({ error: "journal_unavailable" });
    const text = req.body && typeof req.body.text === "string" ? req.body.text : "";
    const tags = Array.isArray(req.body && req.body.tags) ? req.body.tags : [];
    if (!text.trim()) return res.status(400).json({ error: "text_required" });
    res.json({ note: j.addNote(text, { tags }) });
  });

  app.use("/api/v1", api);

  app.use((_req, res) => {
    res.status(404).json({ error: "not_found" });
  });

  const server = http.createServer(app);
  const wss = new WebSocketServer({ noServer: true });
  const clients = new Set();

  server.on("upgrade", (req, socket, head) => {
    const url = req.url || "";
    if (!url.startsWith("/ws")) {
      socket.destroy();
      return;
    }
    const auth = getAuth();
    if (!auth.enabled || !auth.token) {
      socket.write("HTTP/1.1 503 Service Unavailable\r\n\r\n");
      socket.destroy();
      return;
    }
    let token = null;
    try {
      const u = new URL(url, "http://x");
      token = u.searchParams.get("token");
    } catch {}
    if (!token || !timingSafeEqualString(token, auth.token)) {
      socket.write("HTTP/1.1 401 Unauthorized\r\n\r\n");
      socket.destroy();
      return;
    }
    wss.handleUpgrade(req, socket, head, (ws) => {
      const remoteAddr = (req.socket.remoteAddress || "?").replace(/^::ffff:/, "");
      const client = {
        ws,
        subscriptions: null, // null = none yet, "*" = all agents, Set<string> = specific
        remoteAddr,
        connectedAt: Date.now(),
        isAlive: true,
        missedPings: 0,
      };
      clients.add(client);
      console.log(`[server] client connected from ${remoteAddr} (total: ${clients.size})`);

      ws.on("close", () => {
        clients.delete(client);
        console.log(`[server] client from ${remoteAddr} disconnected (total: ${clients.size})`);
      });
      ws.on("error", () => {});

      ws.on("message", (data) => {
        let msg;
        try { msg = JSON.parse(data.toString()); } catch { return; }
        if (!msg || typeof msg !== "object") return;

        if (msg.type === "subscribe") {
          if (msg.agentIds === "*") {
            client.subscriptions = "*";
          } else if (Array.isArray(msg.agentIds)) {
            client.subscriptions = new Set(msg.agentIds.filter((x) => typeof x === "string"));
          } else {
            try { ws.send(JSON.stringify({ type: "error", message: "invalid_subscribe" })); } catch {}
            return;
          }
          try { ws.send(JSON.stringify({ type: "subscribed", agentIds: msg.agentIds })); } catch {}
        } else if (msg.type === "unsubscribe") {
          client.subscriptions = null;
          try { ws.send(JSON.stringify({ type: "unsubscribed" })); } catch {}
        } else if (msg.type === "pong") {
          client.isAlive = true;
          client.missedPings = 0;
        }
      });

      // Send a hello so the client knows the connection is live.
      try {
        ws.send(JSON.stringify({ type: "hello", version: version || null, serverTime: Date.now() }));
      } catch {}
    });
  });

  return new Promise((resolve, reject) => {
    const onError = (err) => {
      server.removeListener("listening", onListen);
      reject(err);
    };
    const onListen = () => {
      server.removeListener("error", onError);

      // Heartbeat: every 20s, terminate any client that's missed too many
      // pings; send a fresh ping to the rest. Clients respond with
      // {type: "pong"} which resets isAlive.
      const heartbeatInterval = setInterval(() => {
        for (const c of clients) {
          if (!c.isAlive) {
            c.missedPings += 1;
            if (c.missedPings >= 2) {
              try { c.ws.terminate(); } catch {}
              clients.delete(c);
              continue;
            }
          }
          c.isAlive = false;
          try { c.ws.send(JSON.stringify({ type: "ping" })); } catch {
            try { c.ws.terminate(); } catch {}
            clients.delete(c);
          }
        }
      }, 20000);
      heartbeatInterval.unref?.();

      state = {
        server,
        wss,
        clients,
        port,
        host,
        manager,
        store,
        dataDir,
        version,
        getAuth,
        heartbeatInterval,
      };
      console.log(`[server] listening on http://${host}:${port}`);
      resolve({ port, host });
    };
    server.once("error", onError);
    server.once("listening", onListen);
    server.listen(port, host);
  });
}

function stopServer() {
  if (!state) return Promise.resolve();
  const { server, clients, heartbeatInterval } = state;
  state = null;

  if (heartbeatInterval) clearInterval(heartbeatInterval);

  for (const c of clients) {
    try { c.ws.terminate(); } catch {}
  }
  clients.clear();

  return new Promise((resolve) => {
    let done = false;
    const finish = () => {
      if (done) return;
      done = true;
      console.log("[server] stopped");
      resolve();
    };
    try { server.close(finish); } catch { finish(); }
    setTimeout(finish, 2000).unref?.();
  });
}

function isRunning() {
  return !!state;
}

function getStatus() {
  if (!state) {
    return { running: false, port: null, host: null, connections: 0 };
  }
  return {
    running: true,
    port: state.port,
    host: state.host,
    connections: state.clients.size,
    clientInfo: [...state.clients].map((c) => ({
      remoteAddr: c.remoteAddr,
      connectedAt: c.connectedAt,
    })),
  };
}

// Lifecycle events affect the global agent registry; clients subscribed
// to anything (even a specific agent) should receive them so the UI can
// update its list. Per-agent stream events (delta/tool/result/etc.) are
// filtered by subscription set so phones don't receive traffic they
// aren't watching.
const LIFECYCLE_TYPES = new Set(["agent:created", "agent:updated", "agent:deleted"]);

// Called by main.js's broadcast() to fan out events to remote clients.
function broadcast(event) {
  if (!state || !event) return;
  const payload = JSON.stringify({ type: "event", event });
  const isLifecycle = LIFECYCLE_TYPES.has(event.type);
  const agentId = event.id != null
    ? String(event.id)
    : (event.agent && event.agent.id != null ? String(event.agent.id) : null);

  for (const c of state.clients) {
    if (c.subscriptions === null) continue;
    let shouldSend = false;
    if (c.subscriptions === "*") shouldSend = true;
    else if (isLifecycle) shouldSend = true;
    else if (agentId && c.subscriptions.has(agentId)) shouldSend = true;
    if (shouldSend) {
      try { c.ws.send(payload); } catch {}
    }
  }
}

module.exports = { startServer, stopServer, isRunning, getStatus, broadcast };
